### ISSUE TITLE
State of the project, make a release?

### ISSUE THREAD

**Issue by jirutka** [okbob/Enumset#1]
What is the state of this project? Does it still work on latest PostgreSQL versions?

If it works, could you please make a release (and tag it in the repository)?

**Comment by okbob** [comment]
I wrote this project as experiment and I newer used it. It is not possible to compile it on latest PostgreSQL. Probably not too hard to fix it - but I have different priorities.  If you want, you can take this project.

**Comment by jirutka** [comment]
I don’t have any specific use case for it at this moment. I just discovered pspg (it’s really awesome!), created an Alpine package for it and then looked to other software from you to package. :)

**Comment by okbob** [comment]
2017-10-08 2:08 GMT+02:00 Jakub Jirutka <notifications@github.com>:

> I don’t have any specific use case for it at this moment. I just
> discovered pspg (it’s really awesome!), created an Alpine package for it
> and then looked to other software from you to package. :)
>
There are two interesting and live packages - orafce and plpgsql_check

**Comment by jirutka** [comment]
Thanks for the tip, I didn’t know about orafce. I’ve created the following packages, they are already in the comunity repo and will be in the upcoming stable release:

* [postgresql-orafce](https://pkgs.alpinelinux.org/package/edge/community/x86_64/postgresql-orafce)
* [postgresql-plpgsql_check](https://pkgs.alpinelinux.org/package/edge/community/x86_64/postgresql-plpgsql_check)
* [pspg](https://pkgs.alpinelinux.org/package/edge/community/x86_64/pspg)
* [pgexportdoc](https://pkgs.alpinelinux.org/package/edge/community/x86_64/pgexportdoc)
* [pgimportdoc](https://pkgs.alpinelinux.org/package/edge/community/x86_64/pgimportdoc)
